apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: prometheus
  name: test-example-app
  namespace: test-monitoring
spec:
  ports:
  - name: web
    port: 8080
  selector:
    app: example-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-example-app
  namespace: test-monitoring
spec:
  replicas: 3
  selector:
    matchLabels:
      app: example-app
  template:
    metadata:
      labels:
        app: example-app
    spec:
      containers:
      - image: fabxc/instrumented_app
        name: example-app
        ports:
        - containerPort: 8080
          name: web
---
apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: test-alertmanager-main
  namespace: test-monitoring
spec:
  replicas: 1
  securityContext: {}
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    k8s-app: prometheus
  name: test-example
  namespace: test-monitoring
spec:
  podMetricsEndpoints:
  - interval: 30s
    port: web
  selector:
    matchLabels:
      k8s-app: prometheus
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    prometheus: k8s
  name: test-example
  namespace: test-monitoring
spec:
  alerting:
    alertmanagers:
    - name: alertmanager-main
      namespace: nagamine-monitoring
      port: web
  replicas: 2
  ruleSelector: {}
  securityContext: {}
  serviceAccountName: prometheus-k8s
  serviceMonitorSelector:
    matchLabels:
      k8s-app: prometheus
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  creationTimestamp: null
  labels:
    prometheus: example
    role: alert-rules
  name: test-prometheus-example-rules
  namespace: test-monitoring
spec:
  groups:
  - name: ./example.rules
    rules:
    - alert: ExampleAlert
      expr: vector(1)
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: prometheus
  name: test-example
  namespace: test-monitoring
spec:
  endpoints:
  - interval: 30s
    port: web
  selector:
    matchLabels:
      k8s-app: prometheus
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: prometheus
  name: test-my-service-monitor
  namespace: test-monitoring
spec:
  endpoints:
  - interval: 30s
    port: web
  selector:
    matchLabels:
      k8s-app: hogehoge
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: prometheus
  name: test-sm-metrics-server
  namespace: test-monitoring
spec:
  endpoints:
  - interval: 30s
    port: web
  selector:
    matchLabels:
      kubernetes.io/name: Metrics-server
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: test-my-prometheus
  namespace: test-monitoring
spec:
  channel: beta
  name: prometheus
  source: operatorhubio-catalog
  sourceNamespace: olm
---
apiVersion: operators.coreos.com/v1alpha2
kind: OperatorGroup
metadata:
  name: test-operatorgroup
  namespace: test-monitoring
spec:
  targetNamespaces:
  - test-monitoring
