apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: my-prometheus
  #namespace: my-prometheu
  namespace: $(NAMESPACE)
spec:
  channel: beta
  name: prometheus
  source: operatorhubio-catalog
  sourceNamespace: olm
